AWSTemplateFormatVersion: '2010-09-09'
Transform: "AWS::Serverless-2016-10-31"

Resources: 
  serverlessDemo:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 3
      CodeUri: .
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /
            Method: get